### ISSUE TITLE
v1 proposal

### ISSUE THREAD

**Issue by cristiandouce** [auth0/id-generator#5]
**API options**
- [ ] Allow to pass a different alphabet for the id generation. Default to current.
- [ ] Allow to accept a variable length of characters for the id
- [ ] Allow to generate ids without prefix (make it optional). It should be a constructor option.

**Example usage:**

``` js
const userIdGen = new IdGenerator({ len: 4, alphabet: 'abcd1234', prefix: 'usr' });
const ticketIdGen = new IdGenerator({ len: 4, prefix: 'tkt' });
const docIdGen = new IdGenerator();

usrIdGen.get() // 'usr_a42c'
ticketIdGen.get() // 'tkt_A2z3'
docIdGen.get() // 'a1Bc2de3fG45hI6...'
```

**Comment by jfromaniello** [comment]
I like this API a lot
